#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"


#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s ${SCRIPTPATH}/down /tmp/leftwm-theme-down


#boot compton or picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom --backend glx -b &> /dev/null &
  #picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

#set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
#if [ -x "$(command -v feh)" ]; then
#  feh --bg-scale "${SCRIPTPATH}/background.jpg"
#fi

#make sure all fonts needed are installed
${SCRIPTPATH}/fonts/install_fonts

# extra utils to make this theme a little more homey
if [ -x "$(command -v dunst)" ]; then
  dunst &
fi

eval $(dbus-launch --sh-syntax --exit-with-x11)
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY XDG_CURRENT_DESKTOP
xbindkeys &
setxkbmap -model pc104 -layout us,bg -variant ,phonetic -option grp:alt_shift_toggle &
xsetroot -cursor_name left_ptr &
xset s on &
xset s 180 120 &
xmodmap ~/.Xmodmap 
wallpaper-picker --image-paths ~/images/ --sleep 14400 &
thunderbird &
# slack &
#/home/iatanaso/bin/modeset &
#boot a polybar for each monitor
cd ${SCRIPTPATH}/polybar
monitors=($(polybar -m | sed s/:.*// | tr -t '\n' ' '))
for mon in  "${monitors[@]}"; do
  MONITOR=$mon polybar -c config.ini main &> /dev/null &
done

